config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users
  resources :universities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :locations, only: [:new, :index, :create, :destroy]
  resources :swaps, only: [:new, :index, :create, :destroy, :show]

  match 'signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get 'help', to: 'pages#help'
  get 'contact', to: 'pages#contact'

end

app/views/layouts/_footer.html.haml
-#%footer{class:"footer"}  
-#  = debug(params) if Rails.env.development?

app/views/layouts/_header.html.haml
#error_explanation.center
  - flash.each do |name, msg|
    = content_tag :div, msg, class: name
= render 'shared/error_messages'
%header.navbar.navbar-fixed-top.navbar-inverse
  .nav
    .container
      = link_to root_path, id: 'logo' do
        = content_tag(:span, "", :class => "")
        Swap Sniper
      -unless signed_in?
        %nav
          %ul.nav.navbar-nav.navbar-right
            %li
              =link_to "Home", root_path
            %li
              =link_to "Sign Up", signup_path
            %li
              =link_to "Sign in", signin_path
      -if signed_in?
        %nav
          %ul.nav.navbar-nav.navbar-right
            %li
              =link_to "Home", root_path
            %li
              =link_to "#{current_user.name}", user_path(current_user)
            %li
              = link_to "Sign out", signout_path, method: "delete"

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>Roomswap | <%=yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <%=yield%>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = "Swap Sniper | " + yield(:title)
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      =yield
      = render 'layouts/footer'